In [1]:
import pandas as pd

Scrivere le istruzioni per caricare i dati del file csv (inventare il link e il nome del file) in un dataframe Pandas chiamato “movies”

In [2]:
movies= pd.read_csv("https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv")
movies

                                  Film    Genre  ... Worldwide Gross  Year
0           Zack and Miri Make a Porno  Romance  ...         $41.94   2008
1                      Youth in Revolt   Comedy  ...         $19.62   2010
2   You Will Meet a Tall Dark Stranger   Comedy  ...         $26.66   2010
3                         When in Rome   Comedy  ...         $43.04   2010
4                What Happens in Vegas   Comedy  ...        $219.37   2008
..                                 ...      ...  ...             ...   ...
72                 Across the Universe  romance  ...         $29.37   2007
73                       A Serious Man    Drama  ...         $30.68   2009
74                  A Dangerous Method    Drama  ...          $8.97   2011
75                          27 Dresses   Comedy  ...        $160.31   2008
76                (500) Days of Summer   comedy  ...         $60.72   2009

[77 rows x 8 columns]

visualizzare le ultime 8 righe del dataframe

In [ ]:
movies.tail(8)

                    Film    Genre  ... Worldwide Gross  Year
69             Enchanted   Comedy  ...        $340.49   2007
70             Dear John    Drama  ...        $114.97   2010
71             Beginners   Comedy  ...         $14.31   2011
72   Across the Universe  romance  ...         $29.37   2007
73         A Serious Man    Drama  ...         $30.68   2009
74    A Dangerous Method    Drama  ...          $8.97   2011
75            27 Dresses   Comedy  ...        $160.31   2008
76  (500) Days of Summer   comedy  ...         $60.72   2009

[8 rows x 8 columns]

visualizzare solo le colonne che contengono il titolo e il genere del film

In [ ]:
movies[["Film","Genre"]]

                                  Film    Genre
0           Zack and Miri Make a Porno  Romance
1                      Youth in Revolt   Comedy
2   You Will Meet a Tall Dark Stranger   Comedy
3                         When in Rome   Comedy
4                What Happens in Vegas   Comedy
..                                 ...      ...
72                 Across the Universe  romance
73                       A Serious Man    Drama
74                  A Dangerous Method    Drama
75                          27 Dresses   Comedy
76                (500) Days of Summer   comedy

[77 rows x 2 columns]

visualizzare le righe del dataframe dalla 20 alla 30

In [ ]:
movies[20:31]

                                   Film      Genre  ... Worldwide Gross  Year
20  The Curious Case of Benjamin Button    Fantasy  ...        $285.43   2008
21                     The Back-up Plan     Comedy  ...         $77.09   2010
22                              Tangled  Animation  ...        $355.01   2010
23                   Something Borrowed    Romance  ...         $60.18   2011
24               She's Out of My League     Comedy  ...         $48.81   2010
25                 Sex and the City Two     Comedy  ...        $288.35   2010
26                   Sex and the City 2     Comedy  ...        $288.35   2010
27                     Sex and the City     Comedy  ...        $415.25   2008
28                          Remember Me      Drama  ...         $55.86   2010
29               Rachel Getting Married      Drama  ...         $16.61   2008
30                             Penelope     Comedy  ...         $20.74   2008

[11 rows x 8 columns]

visualizzare i titolo e l’anno dei film che si trovano nelle posizioni 23, 29 e 45

In [ ]:
movies.iloc[[[23,29,45]][["Film","Year"]]]

visualizzare i titoli dei film del genere “Animation”

In [ ]:
movies[movies["Genre"]=="Animation"]["Film"]

6                WALL-E
22              Tangled
64    Gnomeo and Juliet
65    Gnomeo and Juliet
Name: Film, dtype: object

visualizzare i titoli dei film prodotti dalla “Disney” e dalla “20th Century Fox”

In [ ]:
movies[(movies["Lead Studio"]=="Disney")|(movies["Lead Studio"]=="Fox")]["Film"]

3                           When in Rome
4                  What Happens in Vegas
6                                 WALL-E
16                          The Proposal
22                               Tangled
44                         Marley and Me
49                    Love & Other Drugs
56                           Just Wright
60    High School Musical 3: Senior Year
64                     Gnomeo and Juliet
65                     Gnomeo and Juliet
69                             Enchanted
75                            27 Dresses
76                  (500) Days of Summer
Name: Film, dtype: object

visualizzare i titoli dei film usciti dal 2005 al 2010

In [ ]:
movies[(movies["Year"]<=2005)|(movies["Year"]<=2010)]["Film"]

0             Zack and Miri Make a Porno
1                        Youth in Revolt
2     You Will Meet a Tall Dark Stranger
3                           When in Rome
4                  What Happens in Vegas
                     ...
70                             Dear John
72                   Across the Universe
73                         A Serious Man
75                            27 Dresses
76                  (500) Days of Summer
Name: Film, Length: 63, dtype: object

visualizzare i film (tutte le colonne) il cui titolo comincia con la lettera W

In [ ]:
movies[movies.Film.str.startswith("W")]["Film"]

3             When in Rome
4    What Happens in Vegas
5      Water For Elephants
6                   WALL-E
7                 Waitress
8      Waiting For Forever
Name: Film, dtype: object

visualizzare l’ “Audience score %” medio dei film del genere “Drama”

In [ ]:
movies[movies["Genre"]=="Drama"]["Audience score %"].mean()

67.23076923076923

visualizzare il numero di film per ogni genere

In [ ]:
movies.groupby("Genre").count()

           Film  Lead Studio  ...  Worldwide Gross  Year
Genre                         ...
Action        1            1  ...                1     1
Animation     4            4  ...                4     4
Comdy         1            1  ...                1     1
Comedy       41           41  ...               41    41
Drama        13           13  ...               13    13
Fantasy       1            1  ...                1     1
Romance      13           13  ...               13    13
Romence       1            1  ...                1     1
comedy        1            1  ...                1     1
romance       1            1  ...                1     1

[10 rows x 7 columns]

diminuire del 10% il valore delle recensioni presenti nel campo “Audience score %”

In [ ]:
movies["Audience score %"]-((movies["Audience score %"]/100)*10)

0     63.0
1     46.8
2     31.5
3     39.6
4     64.8
      ...
72    75.6
73    57.6
74    80.1
75    63.9
76    72.9
Name: Audience score %, Length: 77, dtype: float64

B

visualizzare le prime 12 righe del dataframe

In [ ]:
df.head(12)#per vedere le prime 10

visualizzare le colonne 3, 4, 5 e 6

In [ ]:
movies.iloc[:,[3,4,5,6]]

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross
0                 70       1.747542                 64         $41.94
1                 52       1.090000                 68         $19.62
2                 35       1.211818                 43         $26.66
3                 44       0.000000                 15         $43.04
4                 72       6.267647                 28        $219.37
..               ...            ...                ...             ...
72                84       0.652603                 54         $29.37
73                64       4.382857                 89         $30.68
74                89       0.448645                 79          $8.97
75                71       5.343622                 40        $160.31
76                81       8.096000                 87         $60.72

[77 rows x 4 columns]

visualizzare le righe del dataframe che si trovano dalla decima alla trentesima posizione

In [ ]:
movies[10:14]

                                   Film    Genre  ... Worldwide Gross  Year
10  Tyler Perry's Why Did I get Married  Romance  ...         $55.86   2007
11              Twilight: Breaking Dawn  Romance  ...        $702.17   2011
12                             Twilight  Romance  ...        $376.66   2008
13                       The Ugly Truth   Comedy  ...        $205.30   2009

[4 rows x 8 columns]

visualizzare il genere e lo studio dei film che si trovano dalla decima alla ventesima posizione

In [8]:
#non capito

visualizzare le informazioni del film “When in Rome”

In [10]:
movies[movies.Film=="When in Rome"]

           Film   Genre Lead Studio  ...  Rotten Tomatoes %  Worldwide Gross  Year
3  When in Rome  Comedy      Disney  ...                 15          $43.04   2010

[1 rows x 8 columns]

visualizzare  le informazioni dei film “When in Rome”, “Waitress” e “WALL-E”

In [12]:
movies[(movies.Film=="When in Rome")|(movies.Film=="“Waitress”")|(movies.Film=="WALL-E")]

           Film      Genre Lead Studio  ...  Rotten Tomatoes %  Worldwide Gross  Year
3  When in Rome     Comedy      Disney  ...                 15          $43.04   2010
6        WALL-E  Animation      Disney  ...                 96         $521.28   2008

[2 rows x 8 columns]

visualizzare i titoli dei film che hanno avuto una recensione di Rotten Tomatoes compresa tra 80 e 90

In [14]:
movies[(movies["Rotten Tomatoes %"]<91)&(movies["Rotten Tomatoes %"]>79)]["Film"]

7                   Waitress
22                   Tangled
29    Rachel Getting Married
39      My Week with Marilyn
57                 Jane Eyre
71                 Beginners
73             A Serious Man
76      (500) Days of Summer
Name: Film, dtype: object

visualizzare i film che hanno la parola “friends” nel titolo

In [ ]:
movies[(movies["Film"].contains("friends"))]["Film"]

visualizzare il valore più alto della recensione di Rotten Tomatoes

In [ ]:
movies[movies["Rotten Tomatoes %"].max()]["Rotten Tomatoes %"]

visualizzare il numero di film per ogni studio

In [21]:
movies.groupby("Lead Studio").count()

                       Film  Genre  ...  Worldwide Gross  Year
Lead Studio                         ...
20th Century Fox          2      2  ...                2     2
CBS                       1      1  ...                1     1
Disney                    8      8  ...                8     8
Fox                       6      6  ...                6     6
Independent              19     19  ...               19    19
Lionsgate                 2      2  ...                2     2
New Line                  1      1  ...                1     1
Paramount                 4      4  ...                4     4
Sony                      4      4  ...                4     4
Summit                    5      5  ...                5     5
The Weinstein Company     3      3  ...                3     3
Universal                 8      8  ...                8     8
Warner Bros.             14     14  ...               14    14

[13 rows x 7 columns]

aumentare del 10% il valore delle recensioni di Rotten Tomatoes

In [23]:
movies["Rotten Tomatoes %"]+((movies["Rotten Tomatoes %"]/100)*10)

0     70.4
1     74.8
2     47.3
3     16.5
4     30.8
      ...
72    59.4
73    97.9
74    86.9
75    44.0
76    95.7
Name: Rotten Tomatoes %, Length: 77, dtype: float64